name: "DEPENDENCIES.md file checker."
description: "DEPENDENCIES.md file checker."
author: "oandriie@redhat.com"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
